/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ExampleDLL */

#ifndef _Included_ExampleDLL
#define _Included_ExampleDLL
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ExampleDLL
 * Method:    mul
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_ExampleDLL_mul
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
